const provincias = {
  "argentina": [
    { "nombre": "Misiones" },
    { "nombre": "San Luis" },
    { "nombre": "San Juan" },
    { "nombre": "Entre Ríos" },
    { "nombre": "Santa Cruz" },
    { "nombre": "Río Negro" },
    { "nombre": "Chubut" },
    { "nombre": "Córdoba" },
    { "nombre": "Mendoza" },
    { "nombre": "La Rioja" },
    { "nombre": "Catamarca" },
    { "nombre": "La Pampa" },
    { "nombre": "Santiago del Estero" },
    { "nombre": "Corrientes" },
    { "nombre": "Santa Fe" },
    { "nombre": "Tucumán" },
    { "nombre": "Neuquén" },
    { "nombre": "Salta" },
    { "nombre": "Chaco" },
    { "nombre": "Formosa" },
    { "nombre": "Jujuy" },
    { "nombre": "Ciudad Autónoma de Buenos Aires" },
    { "nombre": "Buenos Aires" },
    { "nombre": "Tierra del Fuego, Antártida e Islas del Atlántico Sur" }
  ],
  "chile": [
    { "nombre": "Arica y Parinacota" },
    { "nombre": "Tarapacá" },
    { "nombre": "Antofagasta" },
    { "nombre": "Atacama" },
    { "nombre": "Coquimbo" },
    { "nombre": "Valparaíso" },
    { "nombre": "Libertador Gral. Bernardo O’Higgins" },
    { "nombre": "Maule" },
    { "nombre": "Ñuble" },
    { "nombre": "Biobío" },
    { "nombre": "Araucanía" },
    { "nombre": "Los Ríos" },
    { "nombre": "Los Lagos" },
    { "nombre": "Aisén del Gral. Carlos Ibáñez del Campo" },
    { "nombre": "Magallanes y de la Antártica Chilena" },
    { "nombre": "Santiago" }
  ],
  "estadosUnidos": [
    { "nombre": "Alabama" },
    { "nombre": "Alaska" },
    { "nombre": "American Samoa" },
    { "nombre": "Arizona" },
    { "nombre": "Arkansas" },
    { "nombre": "California" },
    { "nombre": "Colorado" },
    { "nombre": "Connecticut" },
    { "nombre": "Delaware" },
    { "nombre": "District Of Columbia" },
    { "nombre": "Federated States Of Micronesia" },
    { "nombre": "Florida" },
    { "nombre": "Georgia" },
    { "nombre": "Guam" },
    { "nombre": "Hawaii" },
    { "nombre": "Idaho" },
    { "nombre": "Illinois" },
    { "nombre": "Indiana" },
    { "nombre": "Iowa" },
    { "nombre": "Kansas" },
    { "nombre": "Kentucky" },
    { "nombre": "Louisiana" },
    { "nombre": "Maine" },
    { "nombre": "Marshall Islands" },
    { "nombre": "Maryland" },
    { "nombre": "Massachusetts" },
    { "nombre": "Michigan" },
    { "nombre": "Minnesota" },
    { "nombre": "Mississippi" },
    { "nombre": "Missouri" },
    { "nombre": "Montana" },
    { "nombre": "Nebraska" },
    { "nombre": "Nevada" },
    { "nombre": "New Hampshire" },
    { "nombre": "New Jersey" },
    { "nombre": "New Mexico" },
    { "nombre": "New York" },
    { "nombre": "North Carolina" },
    { "nombre": "North Dakota" },
    { "nombre": "Northern Mariana Islands" },
    { "nombre": "Ohio" },
    { "nombre": "Oklahoma" },
    { "nombre": "Oregon" },
    { "nombre": "Palau" },
    { "nombre": "Pennsylvania" },
    { "nombre": "Puerto Rico" },
    { "nombre": "Rhode Island" },
    { "nombre": "South Carolina" },
    { "nombre": "South Dakota" },
    { "nombre": "Tennessee" },
    { "nombre": "Texas" },
    { "nombre": "Utah" },
    { "nombre": "Vermont" },
    { "nombre": "Virgin Islands" },
    { "nombre": "Virginia" },
    { "nombre": "Washington" },
    { "nombre": "West Virginia" },
    { "nombre": "Wisconsin" },
    { "nombre": "Wyoming" }
  ],
  "mexico": [
    { "nombre": "AGUASCALIENTES" },
    { "nombre": "BAJA CALIFORNIA" },
    { "nombre": "BAJA CALIFORNIA SUR" },
    { "nombre": "CHIHUAHUA" },
    { "nombre": "CHIAPAS" },
    { "nombre": "CAMPECHE" },
    { "nombre": "CIUDAD DE MEXICO" },
    { "nombre": "COAHUILA" },
    { "nombre": "COLIMA" },
    { "nombre": "DURANGO" },
    { "nombre": "GUERRERO" },
    { "nombre": "GUANAJUATO" },
    { "nombre": "HIDALGO" },
    { "nombre": "JALISCO" },
    { "nombre": "MICHOACAN" },
    { "nombre": "ESTADO DE MEXICO" },
    { "nombre": "MORELOS" },
    { "nombre": "NAYARIT" },
    { "nombre": "NUEVO LEON" },
    { "nombre": "OAXACA" },
    { "nombre": "PUEBLA" },
    { "nombre": "QUINTANA ROO" },
    { "nombre": "QUERETARO" },
    { "nombre": "SINALOA" },
    { "nombre": "SAN LUIS POTOSI" },
    { "nombre": "SONORA" },
    { "nombre": "TABASCO" },
    { "nombre": "TLAXCALA" },
    { "nombre": "TAMAULIPAS" },
    { "nombre": "VERACRUZ" },
    { "nombre": "YUCATAN" },
    { "nombre": "ZACATECAS" }
  ]
}

export default provincias